### ISSUE TITLE
faq 2번째 질문 링크 누락

### ISSUE THREAD

**Issue by hoony-o-1** [creativecommonskorea/cclguide#14]
## 나는 뮤지션입니다. CCL을 이용하면서도 여전히 내 음악에 대해 저작권료를 받을 수 있나요?

CCL 중 ‘비영리’ 옵션이 포함된 라이선스를 선택한다면 가능합니다. (예: CC BY-NC, BY-NC-SA, BY-NC-ND. 자세한 풀이는 **여기**를 클릭해 참조하세요.) 이러한 라이선스는 저작물의 상업적 사용에 대한 저작권료를 받기 위해서 권리를 유보하고 있기 때문입니다.

이에 반해 CCL 중 다른 사람들에게 저작물의 상업적 사용을 허락하는 라이선스(CC BY, CC BY-SA, CC BY-ND)는 이러한 권리를 포기한 것을 의미합니다.

**Comment by mozodev** [comment]
@jyoh0131 
http://cckorea.org/xe/index.php?mid=frequently&document_srl=594 
이글과 같은 원고라 보니까 아래 링크가 걸려있네요.
http://cckorea.org/xe/ccl

```
[여기](http://cckorea.org/xe/ccl){: target="_blank" }
```

cckorea.org 홈페이지도 리뉴얼할 경우에는 저 링크가 유효해지지 않으니까 상의하셔서 원고 수정하시면 되겠습니다.
위의 코드로 교체하면 새 창으로 홈페이지 링크가 걸립니다. 그럼~

**Comment by jyoh0131** [comment]
넵 감사합니다.
